const AccountSConst = {
  GET_FMCSA_DATA_SUCCESS: "GET_FMCSA_DATA_SUCCESS",
  GET_FMCSA_DATA_REQUEST: "GET_FMCSA_DATA_REQUEST",
  GET_FMCSA_DATA_FAILURE: "GET_FMCSA_DATA_FAILURE",
  POST_FMCSA_DATA_REQUEST: "POST_FMCSA_DATA_REQUEST",
  POST_FMCSA_DATA_SUCCESS: "POST_FMCSA_DATA_SUCCESS",
  POST_FMCSA_DATA_FAILURE: "POST_FMCSA_DATA_FAILURE",
  POST_RESIZE_SIGNATURE: "POST_RESIZE_SIGNATURE",
  GET_DRIVER_LIST_REQUEST: "GET_DRIVER_LIST_REQUEST",
  GET_DRIVER_LIST_SUCCESS: "GET_DRIVER_LIST_SUCCESS",
  GET_DRIVER_LIST_FAILURE: "GET_DRIVER_LIST_FAILURE",
  GET_STATES_REQUEST: "GET_STATES_REQUEST",
  GET_STATES_SUCCESS: "GET_STATES_SUCCESS",
  GET_STATES_FAILURE: "GET_STATES_FAILURE",
  GET_CITIES_REQUEST: "GET_CITIES_REQUEST",
  GET_CITIES_SUCCESS: "GET_CITIES_SUCCESS",
  GET_CITIES_FAILURE: "GET_CITIES_FAILURE",
  GET_MAILING_STATES_REQUEST: "GET_MAILING_STATES_REQUEST",
  GET_MAILING_STATES_SUCCESS: "GET_MAILING_STATES_SUCCESS",
  GET_MAILING_STATES_FAILURE: "GET_MAILING_STATES_FAILURE",
  GET_MAILING_CITIES_REQUEST: "GET_MAILING_CITIES_REQUEST",
  GET_MAILING_CITIES_SUCCESS: "GET_MAILING_CITIES_SUCCESS",
  GET_MAILING_CITIES_FAILURE: "GET_MAILING_CITIES_FAILURE",
  POST_DATA_COMPANY_REQUEST: "POST_DATA_COMPANY_REQUEST",
  POST_DATA_COMPANY_SUCCESS: "POST_DATA_COMPANY_SUCCESS",
  POST_DATA_COMPANY_FAILURE: "POST_DATA_COMPANY_FAILURE",
  GET_DATA_COMPANY_REQUEST: "GET_DATA_COMPANY_REQUEST",
  GET_DATA_COMPANY_SUCCESS: "GET_DATA_COMPANY_SUCCESS",
  GET_DATA_COMPANY_FAILURE: "GET_DATA_COMPANY_FAILURE",
  POST_COMPANY_SIGNATURE_REQUEST: "POST_COMPANY_SIGNATURE_REQUEST",
  POST_COMPANY_SIGNATURE_SUCCESS: "POST_COMPANY_SIGNATURE_SUCCESS",
  POST_COMPANY_SIGNATURE_FAILURE: "POST_COMPANY_SIGNATURE_FAILURE",
  POST_COMPANY_USER_REQUEST: "POST_COMPANY_USER_REQUEST",
  POST_COMPANY_USER_SUCCESS: "POST_COMPANY_USER_SUCCESS",
  POST_COMPANY_USER_FAILURE: "POST_COMPANY_USER_FAILURE",
  POST_DATA_USER_REQUEST: "POST_DATA_USER_REQUEST",
  POST_DATA_USER_SUCCESS: "POST_DATA_USER_SUCCESS",
  POST_DATA_USER_FAILURE: "POST_DATA_USER_FAILURE",
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",
  NEW_USER_TOGGLE: "NEW_USER_TOGGLE",
  ADD_CARD_MODAL_TOGGLE: "ADD_CARD_MODAL_TOGGLE",
  DELETE_USERS_REQUEST: "DELETE_USERS_REQUEST",
  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
  DELETE_USERS_FAILURE: "DELETE_USERS_FAILURE",
  DELETE_USER_TOGGLE: "DELETE_USER_TOGGLE",
  REACTIVATE_USERS_REQUEST: "REACTIVATE_USERS_REQUEST",
  REACTIVATE_USERS_SUCCESS: "REACTIVATE_USERS_SUCCESS",
  REACTIVATE_USERS_FAILURE: "REACTIVATE_USERS_FAILURE",
  REACTIVATE_USER_TOGGLE: "REACTIVATE_USER_TOGGLE",

  UPLOAD_DOCS_TOGGLE: "UPLOAD_DOCS_TOGGLE",
  DELETE_DOCUMENT_TOGGLE_C: "DELETE_DOCUMENT_TOGGLE_C",
  DELETE_DOCUMENT_TOGGLE_FILESCOMPANY: "DELETE_DOCUMENT_TOGGLE_FILESCOMPANY",
  TOGGLE_DELETE_FILES_MODAL: "TOGGLE_DELETE_FILES_MODAL",
  TOGGLE_USDOT_DOCUMENTS_MODAL: "TOGGLE_USDOT_DOCUMENTS_MODAL",
  TOGGLE_DRUG_TESTING_DOCUMENTS_MODAL: "TOGGLE_DRUG_TESTING_DOCUMENTS_MODAL",

  POST_SAVE_DOCUMENT_REQUEST: "POST_SAVE_DOCUMENT_REQUEST",
  POST_SAVE_DOCUMENT_SUCCESS: "POST_SAVE_DOCUMENT_SUCCESS",
  POST_SAVE_DOCUMENT_FAILURE: "POST_SAVE_DOCUMENT_FAILURE",
  GET_ALL_DOCUMENTS_REQUEST: "GET_ALL_DOCUMENTS_REQUEST",
  GET_ALL_DOCUMENTS_SUCCESS: "GET_ALL_DOCUMENTS_SUCCESS",
  GET_ALL_DOCUMENTS_FAILURE: "GET_ALL_DOCUMENTS_FAILURE",
  GET_DOCUMENTS_REQUEST: "GET_DOCUMENTS_REQUEST",
  GET_DOCUMENTS_SUCCESS: "GET_DOCUMENTS_SUCCESS",
  GET_DOCUMENTS_FAILURE: "GET_DOCUMENTS_FAILURE",
  DELETE_DOCUMENT_REQUEST_C: "DELETE_DOCUMENT_REQUEST_C",
  DELETE_DOCUMENT_SUCCESS_C: "DELETE_DOCUMENT_SUCCESS_C",
  DELETE_DOCUMENT_FAILURE_C: "DELETE_DOCUMENT_FAILURE_C",
  DELETE_DOCUMENT_REQUEST_H: "DELETE_DOCUMENT_REQUEST_H",
  DELETE_DOCUMENT_SUCCESS_H: "DELETE_DOCUMENT_SUCCESS_H",
  DELETE_DOCUMENT_FAILURE_H: "DELETE_DOCUMENT_FAILURE_H",
  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAILURE: "DOWNLOAD_DOCUMENT_FAILURE",

  OPEN_OPERATION_CLASSIFICATIONS_TOGGLE:
    "OPEN_OPERATION_CLASSIFICATIONS_TOGGLE",
  POST_OPERATION_CLASSIFICATIONS_REQUEST:
    "POST_OPERATION_CLASSIFICATIONS_REQUEST",
  POST_OPERATION_CLASSIFICATIONS_SUCCESS:
    "POST_OPERATION_CLASSIFICATIONS_SUCCESS",
  POST_OPERATION_CLASSIFICATIONS_FAILURE:
    "POST_OPERATION_CLASSIFICATIONS_FAILURE",
  GET_OPERATION_CLASSIFICATIONS_REQUEST:
    "GET_OPERATION_CLASSIFICATIONS_REQUEST",
  GET_OPERATION_CLASSIFICATIONS_SUCCESS:
    "GET_OPERATION_CLASSIFICATIONS_SUCCESS",
  GET_OPERATION_CLASSIFICATIONS_FAILURE:
    "GET_OPERATION_CLASSIFICATIONS_FAILURE",

  OPEN_CLASSIFICATIONS_TOGGLE: "OPEN_CLASSIFICATIONS_TOGGLE",
  POST_CARGO_CLASSIFICATIONS_REQUEST: "POST_CARGO_CLASSIFICATIONS_REQUEST",
  POST_CARGO_CLASSIFICATIONS_SUCCESS: "POST_CARGO_CLASSIFICATIONS_SUCCESS",
  POST_CARGO_CLASSIFICATIONS_FAILURE: "POST_CARGO_CLASSIFICATIONS_FAILURE",
  GET_CARGO_CLASSIFICATIONS_REQUEST: "GET_CARGO_CLASSIFICATIONS_REQUEST",
  GET_CARGO_CLASSIFICATIONS_SUCCESS: "GET_CARGO_CLASSIFICATIONS_SUCCESS",
  GET_CARGO_CLASSIFICATIONS_FAILURE: "GET_CARGO_CLASSIFICATIONS_FAILURE",

  OPEN_HAZARDOUS_MATERIALS_TOGGLE: "OPEN_HAZARDOUS_MATERIALS_TOGGLE",
  GET_HAZARD_MATERIAL_REQUEST: "GET_HAZARD_MATERIAL_REQUEST",
  GET_HAZARD_MATERIAL_SUCCESS: "GET_HAZARD_MATERIAL_SUCCESS",
  GET_HAZARD_MATERIAL_FAILURE: "GET_HAZARD_MATERIAL_FAILURE",
  SAVE_HAZARD_MATERIAL_REQUEST: "SAVE_HAZARD_MATERIAL_REQUEST",
  SAVE_HAZARD_MATERIAL_SUCCESS: "SAVE_HAZARD_MATERIAL_SUCCESS",
  SAVE_HAZARD_MATERIAL_FAILURE: "SAVE_HAZARD_MATERIAL_FAILURE",

  GET_FORM_DATA_REQUEST: "GET_FORM_DATA_REQUEST",
  GET_FORM_DATA_SUCCESS: "GET_FORM_DATA_SUCCESS",
  GET_FORM_DATA_FAILURE: "GET_FORM_DATA_FAILURE",

  GET_ACCIDENT_REGISTRY_REQUEST: "GET_ACCIDENT_REGISTRY_REQUEST",
  GET_ACCIDENT_REGISTRY_SUCCESS: "GET_ACCIDENT_REGISTRY_SUCCESS",
  GET_ACCIDENT_REGISTRY_FAILURE: "GET_ACCIDENT_REGISTRY_FAILURE",
  GET_ACCIDENT_DATA_REQUEST: "GET_ACCIDENT_DATA_REQUEST",
  GET_ACCIDENT_DATA_SUCCESS: "GET_ACCIDENT_DATA_SUCCESS",
  GET_ACCIDENT_DATA_FAILURE: "GET_ACCIDENT_DATA_FAILURE",
  GET_ACCIDENT_REGISTRY_PDF_REQUEST: "GET_ACCIDENT_REGISTRY_PDF_REQUEST",
  GET_ACCIDENT_REGISTRY_PDF_SUCCESS: "GET_ACCIDENT_REGISTRY_PDF_SUCCESS",
  GET_ACCIDENT_REGISTRY_PDF_FAILURE: "GET_ACCIDENT_REGISTRY_PDF_FAILURE",

  ATTACH_PAYMENT_METHOD_REQUEST: "ATTACH_PAYMENT_METHOD_REQUEST",
  ATTACH_PAYMENT_METHOD_SUCCESS: "ATTACH_PAYMENT_METHOD_SUCCESS",
  ATTACH_PAYMENT_METHOD_FAILURE: "ATTACH_PAYMENT_METHOD_FAILURE",

  DETACH_PAYMENT_METHOD_REQUEST: "DETACH_PAYMENT_METHOD_REQUEST",
  DETACH_PAYMENT_METHOD_SUCCESS: "DETACH_PAYMENT_METHOD_SUCCESS",
  DETACH_PAYMENT_METHOD_FAILURE: "DETACH_PAYMENT_METHOD_FAILURE",

  GET_PAYMENT_METHOD_REQUEST: "GET_PAYMENT_METHOD_REQUEST",
  GET_PAYMENT_METHOD_SUCCESS: "GET_PAYMENT_METHOD_SUCCESS",
  GET_PAYMENT_METHOD_FAILURE: "GET_PAYMENT_METHOD_FAILURE",

  GET_DEFAULT_PAYMENT_REQUEST: "GET_DEFAULT_PAYMENT_REQUEST",
  GET_DEFAULT_PAYMENT_SUCCESS: "GET_DEFAULT_PAYMENT_SUCCESS",
  GET_DEFAULT_PAYMENT_FAILURE: "GET_DEFAULT_PAYMENT_FAILURE",

  SET_DEFAULT_PAYMENT_REQUEST: "SET_DEFAULT_PAYMENT_REQUEST",
  SET_DEFAULT_PAYMENT_SUCCESS: "SET_DEFAULT_PAYMENT_SUCCESS",
  SET_DEFAULT_PAYMENT_FAILURE: "SET_DEFAULT_PAYMENT_FAILURE",

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  
  UPLOAD_FILE_REQUEST_UCR: "UPLOAD_FILE_REQUEST_UCR",
  UPLOAD_FILE_SUCCESS_UCR: "UPLOAD_FILE_SUCCESS_UCR",
  UPLOAD_FILE_FAILURE_UCR: "UPLOAD_FILE_FAILURE_UCR",

  RESET_MESSAGE: "RESET_MESSAGE",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  TOGGLE_TOAST_ALERT_HAZMAT: "TOGGLE_TOAST_ALERT_HAZMAT",
  TOGGLE_TOAST_ALERT_HAZMATS: "TOGGLE_TOAST_ALERT_HAZMATS",

  GET_ACCIDENT_REGISTER_DOCUMENTS_REQUEST:
    "GET_ACCIDENT_REGISTER_DOCUMENTS_REQUEST",
  GET_ACCIDENT_REGISTER_DOCUMENTS_SUCCESS:
    "GET_ACCIDENT_REGISTER_DOCUMENTS_SUCCESS",
  GET_ACCIDENT_REGISTER_DOCUMENTS_FAILURE:
    "GET_ACCIDENT_REGISTER_DOCUMENTS_FAILURE",

  GET_ALL_HAZMAT_DOCS_REQUEST: "GET_ALL_HAZMAT_DOCS_REQUEST",
  GET_ALL_HAZMAT_DOCS_SUCCESS: "GET_ALL_HAZMAT_DOCS_SUCCESS",
  GET_ALL_HAZMAT_DOCS_FAILURE: "GET_ALL_HAZMAT_DOCS_FAILURE",

  GET_COMPANY_INSURANCE_INFO_REQUEST: "GET_COMPANY_INSURANCE_INFO_REQUEST",
  GET_COMPANY_INSURANCE_INFO_SUCCESS: "GET_COMPANY_INSURANCE_INFO_SUCCESS",
  GET_COMPANY_INSURANCE_INFO_FAILURE: "GET_COMPANY_INSURANCE_INFO_FAILURE",

  ADD_COMPANY_INSURANCE_INFO_REQUEST: "ADD_COMPANY_INSURANCE_INFO_REQUEST",
  ADD_COMPANY_INSURANCE_INFO_SUCCESS: "ADD_COMPANY_INSURANCE_INFO_SUCCESS",
  ADD_COMPANY_INSURANCE_INFO_FAILURE: "ADD_COMPANY_INSURANCE_INFO_FAILURE",

  GET_ALL_HAZMAT_TRAINING_DOC_REQUEST: "GET_ALL_HAZMAT_TRAINING_DOC_REQUEST",
  GET_ALL_HAZMAT_TRAINING_DOC_SUCCESS: "GET_ALL_HAZMAT_TRAINING_DOC_SUCCESS",
  GET_ALL_HAZMAT_TRAINING_DOC_FAILURE: "GET_ALL_HAZMAT_TRAINING_DOC_FAILURE",

  UPLOAD_ALL_HAZMAT_TRAINING_DOC_REQUEST:
    "UPLOAD_ALL_HAZMAT_TRAINING_DOC_REQUEST",
  UPLOAD_ALL_HAZMAT_TRAINING_DOC_SUCCESS:
    "UPLOAD_ALL_HAZMAT_TRAINING_DOC_SUCCESS",
  UPLOAD_ALL_HAZMAT_TRAINING_DOC_FAILURE:
    "UPLOAD_ALL_HAZMAT_TRAINING_DOC_FAILURE",

  UPLOAD_SECURITY_PLAN_REQUEST: "UPLOAD_SECURITY_PLAN_REQUEST",
  UPLOAD_SECURITY_PLAN_SUCCESS: "UPLOAD_SECURITY_PLAN_SUCCESS",
  UPLOAD_SECURITY_PLAN_FAILURE: "UPLOAD_SECURITY_PLAN_FAILURE",

  UPLOAD_DRIVERS_DOCS_REQUEST: "UPLOAD_DRIVERS_DOCS_REQUEST",
  UPLOAD_DRIVERS_DOCS_SUCCESS: "UPLOAD_DRIVERS_DOCS_SUCCESS",
  UPLOAD_DRIVERS_DOCS_FAILURE: "UPLOAD_DRIVERS_DOCS_FAILURE",

  UPLOAD_DRIVERS_DOCS_HAZMAT_REQUEST: "UPLOAD_DRIVERS_DOCS_HAZMAT_REQUEST",
  UPLOAD_DRIVERS_DOCS_HAZMAT_SUCCESS: "UPLOAD_DRIVERS_DOCS_HAZMAT_SUCCESS",
  UPLOAD_DRIVERS_DOCS_HAZMAT_FAILURE: "UPLOAD_DRIVERS_DOCS_HAZMAT_FAILURE",

  UPLOAD_DRIVERS_DOCS_HAZMATS_REQUEST: "UPLOAD_DRIVERS_DOCS_HAZMATS_REQUEST",
  UPLOAD_DRIVERS_DOCS_HAZMATS_SUCCESS: "UPLOAD_DRIVERS_DOCS_HAZMATS_SUCCESS",
  UPLOAD_DRIVERS_DOCS_HAZMATS_FAILURE: "UPLOAD_DRIVERS_DOCS_HAZMATS_FAILURE",

  GET_ALL_DOCUMENTS_REQUEST_DRIVERS: "GET_ALL_DOCUMENTS_REQUEST_DRIVERS",
  GET_ALL_DOCUMENTS_SUCCESS_DRIVERS: "GET_ALL_DOCUMENTS_SUCCESS_DRIVERS",
  GET_ALL_DOCUMENTS_FAILURE_DRIVERS: "GET_ALL_DOCUMENTS_FAILURE_DRIVERS",

  DELETE_DRIVERS_DOCS_REQUEST: "DELETE_DRIVERS_DOCS_REQUEST",
  DELETE_DRIVERS_DOCS_SUCCESS: "DELETE_DRIVERS_DOCS_SUCCESS",
  DELETE_DRIVERS_DOCS_FAILURE: "DELETE_DRIVERS_DOCS_FAILURE",

  UPLOAD_DRIVERS_DOCS_TRAINING_REQUEST: "UPLOAD_DRIVERS_DOCS_TRAINING_REQUEST",
  UPLOAD_DRIVERS_DOCS_TRAINING_SUCCESS: "UPLOAD_DRIVERS_DOCS_TRAINING_SUCCESS",
  UPLOAD_DRIVERS_DOCS_TRAINING_FAILURE: "UPLOAD_DRIVERS_DOCS_TRAINING_FAILURE",

  SAVE_CREDENTIALSCH_REQUEST: "SAVE_CREDENTIALSCH_REQUEST",
  SAVE_CREDENTIALSCH_SUCCESS: "SAVE_CREDENTIALSCH_SUCCESS",
  SAVE_CREDENTIALSCH_FAILURE: "SAVE_CREDENTIALSCH_FAILURE",

  GET_CREDENTIALSCH_REQUEST: "GET_CREDENTIALSCH_REQUEST",
  GET_CREDENTIALSCH_SUCCESS: "GET_CREDENTIALSCH_SUCCESS",
  GET_CREDENTIALSCH_FAILURE: "GET_CREDENTIALSCH_FAILURE",

  GET_ACTIVEVEHICLES_REQUEST: "GET_ACTIVEVEHICLES_REQUEST",
  GET_ACTIVEVEHICLES_SUCCESS: "GET_ACTIVEVEHICLES_SUCCESS",
  GET_ACTIVEVEHICLES_FAILURE: "GET_ACTIVEVEHICLES_FAILURE",

  GET_COMPANY_NOTIFICATIONS_REQUEST: "GET_COMPANY_NOTIFICATIONS_REQUEST",
  GET_COMPANY_NOTIFICATIONS_SUCCESS: "GET_COMPANY_NOTIFICATIONS_SUCCESS",
  GET_COMPANY_NOTIFICATIONS_FAILURE: "GET_COMPANY_NOTIFICATIONS_FAILURE",

  UPDATE_COMPANY_NOTIFICATIONS_REQUEST: "UPDATE_COMPANY_NOTIFICATIONS_REQUEST",
  UPDATE_COMPANY_NOTIFICATIONS_SUCCESS: "UPDATE_COMPANY_NOTIFICATIONS_SUCCESS",
  UPDATE_COMPANY_NOTIFICATIONS_FAILURE: "UPDATE_COMPANY_NOTIFICATIONS_FAILURE",

  GET_TRAILERS_REQUEST: "GET_TRAILERS_REQUEST",
  GET_TRAILERS_SUCCESS: "GET_TRAILERS_SUCCESS",
  GET_TRAILERS_FAILURE: "GET_TRAILERS_FAILURE",

  DELETE_DOCUMENT_TRAINING_CERTIFICATE_REQUEST:
    "DELETE_DOCUMENT_TRAINING_CERTIFICATE_REQUEST",
  DELETE_DOCUMENT_TRAINING_CERTIFICATE_SUCCESS:
    "DELETE_DOCUMENT_TRAINING_CERTIFICATE_SUCCESS",
  DELETE_DOCUMENT_TRAINING_CERTIFICATE_FAILURE:
    "DELETE_DOCUMENT_TRAINING_CERTIFICATE_FAILURE",

  DELETE_DRIVERS_DOCS_HAZMAT_REQUEST: "DELETE_DRIVERS_DOCS_HAZMAT_REQUEST",
  DELETE_DRIVERS_DOCS_HAZMAT_SUCCESS: "DELETE_DRIVERS_DOCS_HAZMAT_SUCCESS",
  DELETE_DRIVERS_DOCS_HAZMAT_FAILURE: "DELETE_DRIVERS_DOCS_HAZMAT_FAILURE",

  DELETE_DRIVERS_DOCS_HAZMATS_REQUEST: "DELETE_DRIVERS_DOCS_HAZMATS_REQUEST",
  DELETE_DRIVERS_DOCS_HAZMATS_SUCCESS: "DELETE_DRIVERS_DOCS_HAZMATS_SUCCESS",
  DELETE_DRIVERS_DOCS_HAZMATS_FAILURE: "DELETE_DRIVERS_DOCS_HAZMATS_FAILURE",

  GET_GENERAL_ALERTS_REQUEST: "GET_GENERAL_ALERTS_REQUEST",
  GET_GENERAL_ALERTS_SUCCESS: "GET_GENERAL_ALERTS_SUCCESS",
  GET_GENERAL_ALERTS_FAILURE: "GET_GENERAL_ALERTS_FAILURE",
};

export default AccountSConst;
