const CompaniesConst = {
  GET_DATA_COMPANIES_REQUEST: "GET_DATA_COMPANIES_REQUEST",
  GET_DATA_COMPANIES_SUCCESS: "GET_DATA_COMPANIES_SUCCESS",
  GET_DATA_COMPANIES_FAILURE: "GET_DATA_COMPANIES_FAILURE",
  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  SET_COMPANY_ID_REQUEST: "SET_COMPANY_ID_REQUEST",
  SET_COMPANY_ID_SUCCESS: "SET_COMPANY_ID_SUCCESS",
  SET_DRIVER_ID: "SET_DRIVER_ID",
}

export default CompaniesConst;