const CompanyProviderConst = {
  GET_DATA_PROVIDER_REQUEST: "GET_DATA_PROVIDER_REQUEST",
  GET_DATA_PROVIDER_SUCCESS: "GET_DATA_PROVIDER_SUCCESS",
  GET_DATA_PROVIDER_FAILURE: "GET_DATA_PROVIDER_FAILURE",

  POST_DATA_PROVIDER_REQUEST: "POST_DATA_PROVIDER_REQUEST",
  POST_DATA_PROVIDER_SUCCESS: "POST_DATA_PROVIDER_SUCCESS",
  POST_DATA_PROVIDER_FAILURE: "POST_DATA_PROVIDER_FAILURE",

  EDIT_DATA_PROVIDER_REQUEST: "EDIT_DATA_PROVIDER_REQUEST",
  EDIT_DATA_PROVIDER_SUCCESS: "EDIT_DATA_PROVIDER_SUCCESS",
  EDIT_DATA_PROVIDER_FAILURE: "EDIT_DATA_PROVIDER_FAILURE",

  CLEAN: "CLEAN",
  CLEAN_MESSAGE_T: "CLEAN_MESSAGE_T",
}
export default CompanyProviderConst;