const DevicesConst = {
  DELETE_SERVICE_TOGGLE: "DELETE_SERVICE_TOGGLE",
  CLEAN: "CLEAN",
  CLEAN_MEDIA_LIST_CARD: "CLEAN_MEDIA_LIST_CARD",
  CLEAN_TOAST_REQUEST: "CLEAN_TOAST_REQUEST",
  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  TOGGLE_ERROR_TOAST_ALERT: "TOGGLE_ERROR_TOAST_ALERT",

  GET_DATA_COMPANIES_REQUEST: "GET_DATA_COMPANIES_REQUEST",
  GET_DATA_COMPANIES_SUCCESS: "GET_DATA_COMPANIES_SUCCESS",
  GET_DATA_COMPANIES_FAILURE: "GET_DATA_COMPANIES_FAILURE",

  //? Get all vehicles
  GET_DATA_VEHICLES_REQUEST: "GET_DATA_VEHICLES_REQUEST",
  GET_DATA_VEHICLES_SUCCESS: "GET_DATA_VEHICLES_SUCCESS",
  GET_DATA_VEHICLES_FAILURE: "GET_DATA_VEHICLES_FAILURE",

  //? Get Alerts for a specific Truck
  GET_DATA_ALERTS_REQUEST: "GET_DATA_ALERTS_REQUEST",
  GET_DATA_ALERTS_SUCCESS: "GET_DATA_ALERTS_SUCCESS",
  GET_DATA_ALERTS_FAILURE: "GET_DATA_ALERTS_FAILURE",

  //? Get Media list for a specific camera
  GET_DATA_MEDIA_LIST_REQUEST: "GET_DATA_MEDIA_LIST_REQUEST",
  GET_DATA_MEDIA_LIST_SUCCESS: "GET_DATA_MEDIA_LIST_SUCCESS",
  GET_DATA_MEDIA_LIST_FAILURE: "GET_DATA_MEDIA_LIST_FAILURE",

  //? Get Media list for a specific camera (card)
  GET_DATA_MEDIA_LIST_CARD_REQUEST: "GET_DATA_MEDIA_LIST_CARD_REQUEST",
  GET_DATA_MEDIA_LIST_CARD_SUCCESS: "GET_DATA_MEDIA_LIST_CARD_SUCCESS",
  GET_DATA_MEDIA_LIST_CARD_FAILURE: "GET_DATA_MEDIA_LIST_CARD_FAILURE",

  //? Get Media data for a specific event
  GET_DATA_MEDIA_DATA_REQUEST: "GET_DATA_MEDIA_DATA_REQUEST",
  GET_DATA_MEDIA_DATA_SUCCESS: "GET_DATA_MEDIA_DATA_SUCCESS",
  GET_DATA_MEDIA_DATA_FAILURE: "GET_DATA_MEDIA_DATA_FAILURE",


  GET_DATA_COMPANIES_REQUEST: "GET_DATA_COMPANIES_REQUEST",
  GET_DATA_COMPANIES_SUCCESS: "GET_DATA_COMPANIES_SUCCESS",
  GET_DATA_COMPANIES_FAILURE: "GET_DATA_COMPANIES_FAILURE",

  POST_DATA_DEVICE_REQUEST: "POST_DATA_DEVICE_REQUEST",
  POST_DATA_DEVICE_SUCCESS: "POST_DATA_DEVICE_SUCCESS",
  POST_DATA_DEVICE_FAILURE: "POST_DATA_DEVICE_FAILURE",

  GET_DATA_DEVICES_REQUEST: "GET_DATA_DEVICES_REQUEST",
  GET_DATA_DEVICES_SUCCESS: "GET_DATA_DEVICES_SUCCESS",
  GET_DATA_DEVICES_FAILURE: "GET_DATA_DEVICES_FAILURE",

  POST_UPDATE_CAMERA_REQUEST: " POST_UPDATE_CAMERA_REQUEST",
  POST_UPDATE_CAMERA_SUCCESS: " POST_UPDATE_CAMERA_SUCCESS",
  POST_UPDATE_CAMERA_FAILURE: " POST_UPDATE_CAMERA_FAILURE",

  GET_DATA_KEY_REQUEST: "GET_DATA_KEYS_REQUEST",
  GET_DATA_KEY_SUCCESS: "GET_DATA_KEYS_SUCCESS",
  GET_DATA_KEY_FAILURE: "GET_DATA_KEYS_FAILURE",

  GET_COMPANY_BY_ID_REQUEST: "GET_COMPANY_BY_ID_REQUEST",
  GET_COMPANY_BY_ID_SUCCESS: "GET_COMPANY_BY_ID_SUCCESS",
  GET_COMPANY_BY_ID_FAILURE: "GET_COMPANY_BY_ID_FAILURE",

  SET_CAMERA_DATA_REQUEST: "SET_CAMERA_DATA_REQUEST",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT"
};

export default DevicesConst;
