const DATConst = {
  DELETE_DRIVER_TOGGLE: "DELETE_DRIVER_TOGGLE",
  RESTORE_DRIVER_TOGGLE: "RESTORE_DRIVER_TOGGLE",
  DELETE_DOC_TOGGLE: "DELETE_DOC_TOGGLE",
  GET_DRIVERS_LIST_REQUEST: "GET_DRIVERS_LIST_REQUEST",
  GET_DRIVERS_LIST_SUCCESS: "GET_DRIVERS_LIST_SUCCESS",
  GET_DRIVERS_LIST_FAILURE: "GET_DRIVERS_LIST_FAILURE",
  ENROLL_DRIVER_TOGGLE: "ENROLL_DRIVER_TOGGLE",
  CONFIRMATION_ENROLL_TOGGLE: "CONFIRMATION_ENROLL_TOGGLE",
  GET_DRIVERS_DAT_REQUEST: "GET_DRIVERS_DAT_REQUEST",
  GET_DRIVERS_DAT_SUCCESS: "GET_DRIVERS_DAT_SUCCESS",
  GET_DRIVERS_DAT_FAILURE: "GET_DRIVERS_DAT_FAILURE",
  GET_NONDOTDRIVERS_DAT_REQUEST: "GET_NONDOTDRIVERS_DAT_REQUEST",
  GET_NONDOTDRIVERS_DAT_SUCCESS: "GET_NONDOTDRIVERS_DAT_SUCCESS",
  GET_NONDOTDRIVERS_DAT_FAILURE: "GET_NONDOTDRIVERS_DAT_FAILURE",
  GET_DRIVERSNE_DAT_REQUEST: "GET_DRIVERSNE_DAT_REQUEST",
  GET_DRIVERSNE_DAT_SUCCESS: "GET_DRIVERSNE_DAT_SUCCESS",
  GET_DRIVERSNE_DAT_FAILURE: "GET_DRIVERSNE_DAT_FAILURE",
  ENROLL_DRIVER_REQUEST: "ENROLL_DRIVER_REQUEST",
  ENROLL_DRIVER_SUCCESS: "ENROLL_DRIVER_SUCCESS",
  ENROLL_DRIVER_FAILURE: "ENROLL_DRIVER_FAILURE",
  EXPORT_ENROLL_DRIVER_REQUEST: "EXPORT_ENROLL_DRIVER_REQUEST",
  EXPORT_ENROLL_DRIVER_SUCCESS: "EXPORT_ENROLL_DRIVER_SUCCESS",
  EXPORT_ENROLL_DRIVER_FAILURE: "EXPORT_ENROLL_DRIVER_FAILURE",

  DRUGSTEST_DOCS_TOGGLE: "DRUGSTEST_DOCS_TOGGLE",
  DELETE_CERTIFICATES_TOGGLE: "DELETE_CERTIFICATES_TOGGLE",
  DELETE_TRAINING_TOGGLE: "DELETE_TRAINING_TOGGLE",
  SAVE_DRUGSTEST_DOCS_REQUEST: "SAVE_DRUGSTEST_DOCS_REQUEST",
  SAVE_DRUGSTEST_DOCS_SUCCESS: "SAVE_DRUGSTEST_DOCS_SUCCESS",
  SAVE_DRUGSTEST_DOCS_FAILURE: "SAVE_DRUGSTEST_DOCS_FAILURE",
  GET_CERTIFICATES_REQUEST: "GET_CERTIFICATES_REQUEST",
  GET_CERTIFICATES_SUCCESS: "GET_CERTIFICATES_SUCCESS",
  GET_CERTIFICATES_FAILURE: "GET_CERTIFICATES_FAILURE",
  DELETE_CERTIFICATES_REQUEST: "DELETE_CERTIFICATES_REQUEST",
  DELETE_CERTIFICATES_SUCCESS: "DELETE_CERTIFICATES_SUCCESS",
  DELETE_CERTIFICATES_FAILURE: "DELETE_CERTIFICATES_FAILURE",
  GET_TRAINING_REQUEST: "GET_TRAINING_REQUEST",
  GET_TRAINING_SUCCESS: "GET_TRAINING_SUCCESS",
  GET_TRAINING_FAILURE: "GET_TRAINING_FAILURE",
  DELETE_TRAINING_REQUEST: "DELETE_TRAINING_REQUEST",
  DELETE_TRAINING_SUCCESS: "DELETE_TRAINING_SUCCESS",
  DELETE_TRAINING_FAILURE: "DELETE_TRAINING_FAILURE",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  TOGGLE_DRUG_TOAST_ALERT: "TOGGLE_DRUG_TOAST_ALERT",
  TOGGLE_DRUG_TEST: "TOGGLE_DRUG_TEST",
  TOGGLE_RANDOM_VALIDATION: "TOGGLE_RANDOM_VALIDATION",
  POST_DRUG_ALCOHOL_TEST_REQUEST: "POST_DRUG_ALCOHOL_TEST_REQUEST",
  POST_DRUG_ALCOHOL_TEST_SUCCESS: "POST_DRUG_ALCOHOL_TEST_SUCCESS",
  POST_DRUG_ALCOHOL_TEST_FAILURE: "POST_DRUG_ALCOHOL_TEST_FAILURE",
  GET_LIST_DRUG_ALCOHOL_TEST_REQUEST: "GET_LIST_DRUG_ALCOHOL_TEST_REQUEST",
  GET_LIST_DRUG_ALCOHOL_TEST_SUCCESS: "GET_LIST_DRUG_ALCOHOL_TEST_SUCCESS",
  GET_LIST_DRUG_ALCOHOL_TEST_FAILURE: "GET_LIST_DRUG_ALCOHOL_TEST_FAILURE",

  DELETE_DRIVER_DOCUMENT_TOGGLE: "DELETE_DRIVER_DOCUMENT_TOGGLE",
  POST_SAVE_DRIVER_DOCUMENT_REQUEST: "POST_DOCUMENT_REQUEST",
  POST_SAVE_DRIVER_DOCUMENT_SUCCESS: "POST_DOCUMENT_SUCCESS",
  POST_SAVE_DRIVER_DOCUMENT_FAILURE: "POST_DOCUMENT_FAILURE",
  GET_ALL_DRIVER_DOCUMENTS_REQUEST: "GET_ALL_DRIVER_DOCUMENTS_REQUEST",
  GET_ALL_DRIVER_DOCUMENTS_SUCCESS: "GET_ALL_DRIVER_DOCUMENTS_SUCCESS",
  GET_ALL_DRIVER_DOCUMENTS_FAILURE: "GET_ALL_DRIVER_DOCUMENTS_FAILURE",
  DOWNLOAD_DOCUMENT_DRIVER_REQUEST: "DOWNLOAD_DOCUMENT_DRIVER_REQUEST",
  DOWNLOAD_DOCUMENT_DRIVER_SUCCESS: "DOWNLOAD_DOCUMENT_DRIVER_SUCCESS",
  DOWNLOAD_DOCUMENT_DRIVER_FAILURE: "DOWNLOAD_DOCUMENT_DRIVER_FAILURE",
  DELETE_DRIVER_DOCUMENT_REQUEST: "DELETE_DRIVER_DOCUMENT_REQUEST",
  DELETE_DRIVER_DOCUMENT_SUCCESS: "DELETE_DRIVER_DOCUMENT_SUCCESS",
  DELETE_DRIVER_DOCUMENTD_FAILURE: "DELETE_DRIVER_DOCUMENT_FAILURE",

  POST_SCHEDULE_DRUG_TEST_REQUEST: "POST_SCHEDULE_DRUG_TEST_REQUEST",
  POST_SCHEDULE_DRUG_TEST_SUCCESS: "POST_SCHEDULE_DRUG_TEST_SUCCESS",
  POST_SCHEDULE_DRUG_TEST_FAILURE: "POST_SCHEDULE_DRUG_TEST_FAILURE",
  GET_SCHEDULE_FOR_DAY_REQUEST: "GET_SCHEDULE_FOR_DAY_REQUEST",
  GET_SCHEDULE_FOR_DAY_SUCCESS: "GET_SCHEDULE_FOR_DAY_SUCCESS",
  GET_SCHEDULE_FOR_DAY_FAILURE: "GET_SCHEDULE_FOR_DAY_FAILURE",
  GET_DRUG_SCHEDULED_TESTS_REQUEST: "GET_DRUG_SCHEDULED_TESTS_REQUEST",
  GET_DRUG_SCHEDULED_TESTS_SUCCESS: "GET_DRUG_SCHEDULED_TESTS_SUCCESS",
  GET_DRUG_SCHEDULED_TESTS_FAILURE: "GET_DRUG_SCHEDULED_TESTS_FAILURE",
  GET_DRUG_SCHEDULED_TEST_DATA_REQUEST: "GET_DRUG_SCHEDULED_TEST_DATA_REQUEST",
  GET_DRUG_SCHEDULED_TEST_DATA_SUCCESS: "GET_DRUG_SCHEDULED_TEST_DATA_SUCCESS",
  GET_DRUG_SCHEDULED_TEST_DATA_FAILURE: "GET_DRUG_SCHEDULED_TEST_DATA_FAILURE",
  CANCEL_SCHEDULED_TOGGLE: "CANCEL_SCHEDULED_TOGGLE",
  DELETE_SCHEDULED_TOGGLE: "DELETE_SCHEDULED_TOGGLE",
  CANCEL_ALCOHOL_SCHEDULED_TOGGLE: "CANCEL_ALCOHOL_SCHEDULED_TOGGLE",
  DELETE_SCHEDULED_ALCOHOL_TOGGLE: "DELETE_SCHEDULED_ALCOHOL_TOGGLE",
  DELETE_DRUG_SCHEDULED_TEST_REQUEST: "DELETE_DRUG_SCHEDULED_TEST_REQUEST",
  DELETE_DRUG_SCHEDULED_TEST_SUCCESS: "DELETE_DRUG_SCHEDULED_TEST_SUCCESS",
  DELETE_DRUG_SCHEDULED_TEST_FAILURE: "DELETE_DRUG_SCHEDULED_TEST_FAILURE",

  GET_PAYMENT_METHOD_REQUEST: "GET_PAYMENT_METHOD_REQUEST",
  GET_PAYMENT_METHOD_SUCCESS: "GET_PAYMENT_METHOD_SUCCESS",
  GET_PAYMENT_METHOD_FAILURE: "GET_PAYMENT_METHOD_FAILURE",
  GET_DEFAULT_PAYMENT_REQUEST: "GET_DEFAULT_PAYMENT_REQUEST",
  GET_DEFAULT_PAYMENT_SUCCESS: "GET_DEFAULT_PAYMENT_SUCCESS",
  GET_DEFAULT_PAYMENT_FAILURE: "GET_DEFAULT_PAYMENT_FAILURE",
  SET_DEFAULT_PAYMENT_REQUEST: "SET_DEFAULT_PAYMENT_REQUEST",
  SET_DEFAULT_PAYMENT_SUCCESS: "SET_DEFAULT_PAYMENT_SUCCESS",
  SET_DEFAULT_PAYMENT_FAILURE: "SET_DEFAULT_PAYMENT_FAILURE",
  CHARGE_TEST_REQUEST: "CHARGE_TEST_REQUEST",
  CHARGE_TEST_SUCCESS: "CHARGE_TEST_SUCCESS",
  CHARGE_TEST_FAILURE: "CHARGE_TEST_FAILURE",
  ADD_CARD_MODAL_TOGGLE: "ADD_CARD_MODAL_TOGGLE",
  ATTACH_PAYMENT_METHOD_REQUEST: "ATTACH_PAYMENT_METHOD_REQUEST",
  ATTACH_PAYMENT_METHOD_SUCCESS: "ATTACH_PAYMENT_METHOD_SUCCESS",
  ATTACH_PAYMENT_METHOD_FAILURE: "ATTACH_PAYMENT_METHOD_FAILURE",

  GET_ALL_DOCUMENTS_REQUEST: "GET_ALL_DOCUMENTS_REQUEST",
  GET_ALL_DOCUMENTS_SUCCESS: "GET_ALL_DOCUMENTS_SUCCESS",
  GET_ALL_DOCUMENTS_FAILURE: "GET_ALL_DOCUMENTS_FAILURE",

  DELETE_DOCUMENT_TOGGLE_FILES_DRUGTEST:
    "DELETE_DOCUMENT_TOGGLE_FILES_DRUGTEST",

  DELETE_DOCUMENT_REQUEST_C: "DELETE_DOCUMENT_REQUEST_C",
  DELETE_DOCUMENT_SUCCESS_C: "DELETE_DOCUMENT_SUCCESS_C",
  DELETE_DOCUMENT_FAILURE_C: "DELETE_DOCUMENT_FAILURE_C",

  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAILURE: "DOWNLOAD_DOCUMENT_FAILURE",

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  GET_DRUG_SCHEDULED_TEST_PROVIDER_REQUEST:
    "GET_DRUG_SCHEDULED_TEST_PROVIDER_REQUEST",
  GET_DRUG_SCHEDULED_TEST_PROVIDER_SUCCESS:
    "GET_DRUG_SCHEDULED_TEST_PROVIDER_SUCCESS",
  GET_DRUG_SCHEDULED_TEST_PROVIDER_FAILURE:
    "GET_DRUG_SCHEDULED_TEST_PROVIDER_FAILURE",
  POST_DRUG_TEST_REQUEST: "POST_DRUG_TEST_REQUEST",
  POST_DRUG_TEST_SUCCESS: "POST_DRUG_TEST_SUCCESS",
  POST_DRUG_TEST_FAILURE: "POST_DRUG_TEST_FAILURE",
  TOGGLE_DRUG_TEST_COLLECTOR: "TOGGLE_DRUG_TEST_COLLECTOR",
  TOGGLE_ALCOHOL_TEST_COLLECTOR: "TOGGLE_ALCOHOL_TEST_COLLECTOR",
  DELETE_DOCUMENT_COLLECTOR_REQUEST: "DELETE_DOCUMENT_COLLECTOR_REQUEST",
  DELETE_DOCUMENT_COLLECTOR_SUCCESS: "DELETE_DOCUMENT_COLLECTOR_SUCCESS",
  DELETE_DOCUMENT_COLLECTOR_FAILURE: "DELETE_DOCUMENT_COLLECTOR_FAILURE",
  DOWNLOAD_DOCUMENT_COLLECTOR_REQUEST: "DOWNLOAD_DOCUMENT_COLLECTOR_REQUEST",
  DOWNLOAD_DOCUMENT_COLLECTOR_SUCCESS: "DOWNLOAD_DOCUMENT_COLLECTOR_SUCCESS",
  DOWNLOAD_DOCUMENT_COLLECTOR_FAILURE: "DOWNLOAD_DOCUMENT_COLLECTOR_FAILURE",
  GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_REQUEST:
    "GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_REQUEST",
  GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_SUCCESS:
    "GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_SUCCESS",
  GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_FAILURE:
    "GET_DRUG_SCHEDULED_TEST_DATA_PROVIDER_FAILURE",

  POST_COLLECTOR_SIGNATURE_REQUEST: "POST_COLLECTOR_SIGNATURE_REQUEST",
  POST_COLLECTOR_SIGNATURE_SUCCESS: "POST_COLLECTOR_SIGNATURE_SUCCESS",
  POST_COLLECTOR_SIGNATURE_FAILURE: "POST_COLLECTOR_SIGNATURE_FAILURE",

  UPDATE_STATUS_SCHEDULE_REQUEST: "UPDATE_STATUS_SCHEDULE_REQUEST",
  UPDATE_STATUS_SCHEDULE_SUCCESS: "UPDATE_STATUS_SCHEDULE_SUCCESS",
  UPDATE_STATUS_SCHEDULE_FAILURE: "UPDATE_STATUS_SCHEDULE_FAILURE",

  CONFIRM_COLLECTOR_SIGNATURE_SUCCESS: "CONFIRM_COLLECTOR_SIGNATURE_SUCCESS",
  CONFIRM_COLLECTOR_SIGNATURE_FAILURE: "CONFIRM_COLLECTOR_SIGNATURE_FAILURE",

  CONFIRM_DONOR_SIGNATURE_SUCCESS: "CONFIRM_DONOR_SIGNATURE_SUCCESS",
  CONFIRM_DONOR_SIGNATURE_FAILURE: "CONFIRM_DONOR_SIGNATURE_FAILURE",
  RESET_MESSAGE: "RESET_MESSAGE",

  POST_NEW_DRIVER_REQUEST: "POST_NEW_DRIVER_REQUEST",
  POST_NEW_DRIVER_SUCCESS: "POST_NEW_DRIVER_SUCCESS",
  POST_NEW_DRIVER_FAILURE: "POST_NEW_DRIVER_FAILURE",

  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAILURE: "GET_COUNTRIES_FAILURE",

  NEW_DRIVER_TOGGLE: "NEW_DRIVER_TOGGLE",

  GET_RANDOM_TEST_REQUEST: "GET_RANDOM_TEST_REQUEST",
  GET_RANDOM_TEST_SUCCESS: "GET_RANDOM_TEST_SUCCESS",
  GET_RANDOM_TEST_FAILURE: "GET_RANDOM_TEST_FAILURE",

  SCHEDULED_TEST_REQUEST: "GET_SCHEDULED_TEST_REQUEST",
  SCHEDULED_TEST_SUCCESS: "SCHEDULED_TEST_SUCCESS",
  SCHEDULED_TEST_FAILURE: "SCHEDULED_TEST_FAILURE",

  RESEND_EMAIL_RANDOM_REQUEST: "RESEND_EMAIL_RANDOM_REQUEST",
  RESEND_EMAIL_RANDOM_SUCCESS: "RESEND_EMAIL_RANDOM_SUCCESS",
  RESEND_EMAIL_RANDOM_FAILURE: "RESEND_EMAIL_RANDOM_FAILURE",

  RESORT_RANDOM_TEST_REQUEST: "RESORT_RANDOM_TEST_REQUEST",
  RESORT_RANDOM_TEST_SUCCESS: "RESORT_RANDOM_TEST_SUCCESS",
  RESORT_RADOM_TEST_FAILURE: "RESORT_RADOM_TEST_FAILURE",

  MAIL_RANDOM_DRUG_TEST_GENERATED_REQUEST: "MAIL_RANDOM_DRUG_TEST_GENERATED_REQUEST",
  MAIL_RANDOM_DRUG_TEST_GENERATED_SUCCESS: "MAIL_RANDOM_DRUG_TEST_GENERATED_SUCCESS",
  MAIL_RANDOM_DRUG_TEST_GENERATED_FAILURE: "MAIL_RANDOM_DRUG_TEST_GENERATED_FAILURE",

  GET_STATS_REQUEST: "GET_STATS_REQUEST",
  GET_STATS_SUCCESS: "GET_STATS_SUCCESS",
  GET_STATS_FAILURE: "GET_STATS_FAILURE",

  FINISH_SCHEDULE_DRUG_TEST_REQUEST: "FINISH_SCHEDULE_DRUG_TEST_REQUEST",
  FINISH_SCHEDULE_DRUG_TEST_SUCCESS: "FINISH_SCHEDULE_DRUG_TEST_SUCCESS",
  FINISH_SCHEDULE_DRUG_TEST_FAILURE: "FINISH_SCHEDULE_DRUG_TEST_FAILURE",

  GET_ALCOHOL_SCHEDULED_TESTS_REQUEST: "GET_ALCOHOL_SCHEDULED_TESTS_REQUEST",
  GET_ALCOHOL_SCHEDULED_TESTS_SUCCESS: "GET_ALCOHOL_SCHEDULED_TESTS_SUCCESS",
  GET_ALCOHOL_SCHEDULED_TESTS_FAILURE: "GET_ALCOHOL_SCHEDULED_TESTS_FAILURE",

  GET_ALCOHOL_SCHEDULED_TEST_DATA_REQUEST:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_REQUEST",
  GET_ALCOHOL_SCHEDULED_TEST_DATA_SUCCESS:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_SUCCESS",
  GET_ALCOHOL_SCHEDULED_TEST_DATA_FAILURE:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_FAILURE",

  CANCEL_ALCOHOL_SCHEDULED_TOGGLE: "CANCEL_ALCOHOL_SCHEDULED_TOGGLE",

  DELETE_ALCOHOL_SCHEDULED_TOGGLE: "DELETE_ALCOHOL_SCHEDULED_TOGGLE",
  DELETE_ALCOHOL_SCHEDULED_TEST_REQUEST:
    "DELETE_ALCOHOL_SCHEDULED_TEST_REQUEST",
  DELETE_ALCOHOL_SCHEDULED_TEST_SUCCESS:
    "DELETE_ALCOHOL_SCHEDULED_TEST_SUCCESS",
  DELETE_ALCOHOL_SCHEDULED_TEST_FAILURE:
    "DELETE_ALCOHOL_SCHEDULED_TEST_FAILURE",

  POST_SCHEDULE_ALCOHOL_TEST_REQUEST: "POST_SCHEDULE_ALCOHOL_TEST_REQUEST",
  POST_SCHEDULE_ALCOHOL_TEST_SUCCESS: "POST_SCHEDULE_ALCOHOL_TEST_SUCCESS",
  POST_SCHEDULE_ALCOHOL_TEST_FAILURE: "POST_SCHEDULE_ALCOHOL_TEST_FAILURE",

  UPDATE_STATUS_ALCOHOL_SCHEDULE_REQUEST:
    "UPDATE_STATUS_ALCOHOL_SCHEDULE_REQUEST",
  UPDATE_STATUS_ALCOHOL_SCHEDULE_SUCCESS:
    "UPDATE_STATUS_ALCOHOL_SCHEDULE_SUCCESS",
  UPDATE_STATUS_ALCOHOL_SCHEDULE_FAILURE:
    "UPDATE_STATUS_ALCOHOL_SCHEDULE_FAILURE",

  FINISH_SCHEDULE_ALCOHOL_TEST_REQUEST: "FINISH_SCHEDULE_DRUG_TEST_REQUEST",
  FINISH_SCHEDULE_ALCOHOL_TEST_SUCCESS: "FINISH_SCHEDULE_DRUG_TEST_SUCCESS",
  FINISH_SCHEDULE_ALCOHOL_TEST_FAILURE: "FINISH_SCHEDULE_DRUG_TEST_FAILURE",

  GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_REQUEST:
    "GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_REQUEST",
  GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_SUCCESS:
    "GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_SUCCESS",
  GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_FAILURE:
    "GET_ALCOHOL_SCHEDULED_TEST_PROVIDER_FAILURE",
  CANCEL_ALCOHOL_SCHEDULED_REQUEST: "CANCEL_ALCOHOL_SCHEDULED_REQUEST",
  CANCEL_ALCOHOL_SCHEDULED_SUCCESS: "CANCEL_ALCOHOL_SCHEDULED_SUCCESS",
  CANCEL_ALCOHOL_SCHEDULED_FAILURE: "CANCEL_ALCOHOL_SCHEDULED_FAILURE",
  GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_SUCCESS:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_SUCCESS",
  GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_REQUEST:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_REQUEST",
  GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_FAILURE:
    "GET_ALCOHOL_SCHEDULED_TEST_DATA_CLIENT_FAILURE",

  GET_DATA_DRIVER_REQUEST: "GET_DATA_DRIVER_REQUEST",
  GET_DATA_DRIVER_SUCCESS: "GET_DATA_DRIVER_SUCCESS",
  GET_DATA_DRIVER_FAILURE: "GET_DATA_DRIVER_FAILURE",

  POST_DATA_DRIVER_REQUEST: "POST_DATA_DRIVER_REQUEST",
  POST_DATA_DRIVER_SUCCESS: "POST_DATA_DRIVER_SUCCESS",
  POST_DATA_DRIVER_FAILURE: "POST_DATA_DRIVER_FAILURE",

  GET_ENROLLMENT_DOCUMENTS_REQUEST: "GET_ENROLLMENT_DOCUMENTS_REQUEST",
  GET_ENROLLMENT_DOCUMENTS_SUCCESS: "GET_ENROLLMENT_DOCUMENTS_SUCCESS",
  GET_ENROLLMENT_DOCUMENTS_FAILURE: "GET_ENROLLMENT_DOCUMENTS_FAILURE",

  // MIS PRUEBA ENDPOINT

  GET_MISREPORT_DOCUMENTS_REQUEST: "GET_MISREPORT_DOCUMENTS_REQUEST",
  GET_MISREPORT_DOCUMENTS_SUCCESS: "GET_MISREPORT_DOCUMENTS_SUCCESS",
  GET_MISREPORT_DOCUMENTS_FAILURE: "GET_MISREPORT_DOCUMENTS_FAILURE",

  POST_MISREPORT_DOCUMENTS_REQUEST: "POST_MISREPORT_DOCUMENTS_REQUEST",
  POST_MISREPORT_DOCUMENTS_SUCCESS: "POST_MISREPORT_DOCUMENTS_SUCCESS",
  POST_MISREPORT_DOCUMENTS_FAILURE: "POST_MISREPORT_DOCUMENTS_FAILURE",

  UPLOADMIS_FILE_REQUEST: "UPLOADMIS_FILE_REQUEST",
  UPLOADMIS_FILE_SUCCESS: "UPLOADMIS_FILE_SUCCESS",
  UPLOADMIS_FILE_FAILURE: "UPLOADMIS_FILE_FAILURE",

  GET_ALL_MISREPORTS_REQUEST: "GET_ALL_MISREPORTS_REQUEST",
  GET_ALL_MISREPORTS_SUCCESS: "GET_ALL_MISREPORTS_SUCCESS",
  GET_ALL_MISREPORTS_FAILURE: "GET_ALL_MISREPORTS_FAILURE",

  GET_DOTDRIVERS_REQUEST: "GET_DOTDRIVERS_REQUEST",
  GET_DOTDRIVERS_SUCCESS: "GET_DOTDRIVERS_SUCCESS",
  GET_DOTDRIVERS_FAILURE: "GET_DOTDRIVERS_FAILURE",

  //Update DoT Driver remove
  UPDATE_DOTDriver_REQUEST: "UPDATE_DOTDriver_REQUEST",
  UPDATE_DOTDriver_SUCCESS: "UPDATE_DOTDriver_SUCCESS",
  UPDATE_DOTDriver_FAILURE: "UPDATE_DOTDriver_FAILURE",
  // MIS PRUEBA ENDPOINT

  DELETE_DATA_STEPPER_SUCCESS: "DELETE_DATA_STEPPER_SUCCESS",

  //ONCHANGE STATE DATA
  POST_FORM_DATA: "POST_FORM_DATA",
};

export default DATConst;
