const NotificationsConst = {
    GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATIONS_REQUEST",
    GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
    GET_NOTIFICATIONS_FAILURE: "GET_NOTIFICATIONS_FAILURE",
    GET_NOTIFICATIONS_MAINTENANCE_REQUEST: "GET_NOTIFICATIONS_MAINTENANCE_REQUEST",
    GET_NOTIFICATIONS_MAINTENANCE_SUCCESS: "GET_NOTIFICATIONS_MAINTENANCE_SUCCESS",
    GET_NOTIFICATIONS_MAINTENANCE_FAILURE: "GET_NOTIFICATIONS_MAINTENANCE_FAILURE",
    GET_NOTIFICATIONS_COMPANY_REQUEST: "GET_NOTIFICATIONS_COMPANY_REQUEST",
    GET_NOTIFICATIONS_COMPANY_SUCCESS: "GET_NOTIFICATIONS_COMPANY_SUCCESS",
    GET_NOTIFICATIONS_COMPANY_FAILURE: "GET_NOTIFICATIONS_COMPANY_FAILURE",
    GET_SAVE_NOTIFICATIONS_REQUEST: "GET_SAVE_NOTIFICATIONS_REQUEST",
    GET_SAVE_NOTIFICATIONS_SUCCESS: "GET_SAVE_NOTIFICATIONS_SUCCESS",
    GET_SAVE_NOTIFICATIONS_FAILURE: "GET_SAVE_NOTIFICATIONS_FAILURE",
    GET_SAVE_NOTIFICATIONSM_REQUEST: "GET_SAVE_NOTIFICATIONSM_REQUEST",
    GET_SAVE_NOTIFICATIONSM_SUCCESS: "GET_SAVE_NOTIFICATIONSM_SUCCESS",
    GET_SAVE_NOTIFICATIONSM_FAILURE: "GET_SAVE_NOTIFICATIONSM_FAILURE",
    GET_SAVE_NOTIFICATIONSC_REQUEST: "GET_SAVE_NOTIFICATIONSC_REQUEST",
    GET_SAVE_NOTIFICATIONSC_SUCCESS: "GET_SAVE_NOTIFICATIONSC_SUCCESS",
    GET_SAVE_NOTIFICATIONSC_FAILURE: "GET_SAVE_NOTIFICATIONSC_FAILURE",
    GET_NOTIFICATIONS_LOGS_REQUEST: "GET_NOTIFICATIONS_LOGS_REQUEST",
    GET_NOTIFICATIONS_LOGS_SUCCESS: "GET_NOTIFICATIONS_LOGS_SUCCESS",
    GET_NOTIFICATIONS_LOGS_FAILURE: "GET_NOTIFICATIONS_LOGS_FAILURE"
  };
  
  export default NotificationsConst;