const TrailersConst = {
  GET_STATES_REQUEST: "GET_STATES_REQUEST",
  GET_STATES_SUCCESS: "GET_STATES_SUCCESS",
  GET_STATES_FAILURE: "GET_STATES_FAILURE",
  GET_TRAILER_REQUEST: "GET_TRAILER_REQUEST",
  GET_TRAILER_SUCCESS: "GET_TRAILER_SUCCESS",
  GET_TRAILER_FAILURE: "GET_TRAILER_FAILURE",
  POST_SAVE_TRAILER_REQUEST: "POST_SAVE_TRAILER_REQUEST",
  POST_SAVE_TRAILER_SUCCESS: "POST_SAVE_TRAILER_SUCCESS",
  POST_SAVE_TRAILER_FAILURE: "POST_SAVE_TRAILER_FAILURE",
  GET_TRAILER_PHOTOS_REQUEST: "GET_TRAILER_PHOTOS_REQUEST",
  GET_TRAILER_PHOTOS_SUCCESS: "GET_TRAILER_PHOTOS_SUCCESS",
  GET_TRAILER_PHOTOS_FAILURE: "GET_TRAILER_PHOTOS_FAILURE",

  POST_SAVE_DATA_TRAILER_INSURANCE_REQUEST:
    "POST_SAVE_DATA_TRAILER_INSURANCE_REQUEST",
  POST_SAVE_DATA_TRAILER_INSURANCE_SUCCESS:
    "POST_SAVE_DATA_TRAILER_INSURANCE_SUCCESS",
  POST_SAVE_DATA_TRAILER_INSURANCE_FAILURE:
    "POST_SAVE_DATA_TRAILER_INSURANCE_FAILURE",

  NEW_DOCUMENT_TOGGLE: "NEW_DOCUMENT_TOGGLE",
  DELETE_TRAILER_DOCUMENT_TOGGLE: "DELETE_TRAILER_DOCUMENT_TOGGLE",
  POST_SAVE_TRAILER_DOCUMENT_REQUEST: "POST_TRAILER_DOCUMENT_REQUEST",
  POST_SAVE_TRAILER_DOCUMENT_SUCCESS: "POST_TRAILER_DOCUMENT_SUCCESS",
  POST_SAVE_TRAILER_DOCUMENT_FAILURE: "POST_TRAILER_DOCUMENT_FAILURE",
  GET_ALL_TRAILER_DOCUMENTS_REQUEST: "GET_ALL_TRAILER_DOCUMENTS_REQUEST",
  GET_ALL_TRAILER_DOCUMENTS_SUCCESS: "GET_ALL_TRAILER_DOCUMENTS_SUCCESS",
  GET_ALL_TRAILER_DOCUMENTS_FAILURE: "GET_ALL_TRAILER_DOCUMENTS_FAILURE",
  DELETE_TRAILER_DOCUMENT_REQUEST: "DELETE_TRAILER_DOCUMENT_REQUEST",
  DELETE_TRAILER_DOCUMENT_SUCCESS: "DELETE_TRAILER_DOCUMENT_SUCCESS",
  DELETE_TRAILER_DOCUMENTD_FAILURE: "DELETE_TRAILER_DOCUMENT_FAILURE",

  OPEN_ALERTS_TOGGLE: "OPEN_ALERTS_TOGGLE",
  GET_TRAILER_ALERTS_REQUEST: "GET_TRAILER_ALERTS_REQUEST",
  GET_TRAILER_ALERTS_SUCCESS: "GET_TRAILER_ALERTS_SUCCESS",
  GET_TRAILER_ALERTS_FAILURE: "GET_TRAILER_ALERTS_FAILURE",

  CLEAN_TRAILER: "CLEAN_TRAILER",
  GET_TRAILER_INSPECTIONS_REQUEST: "GET_TRAILER_INSPECTIONS_REQUEST",
  GET_TRAILER_INSPECTIONS_SUCCESS: "GET_TRAILER_INSPECTIONS_SUCCESS",
  GET_TRAILER_INSPECTIONS_FAILURE: "GET_TRAILER_INSPECTIONS_FAILURE",
  GET_TRAILER_VIOLATIONS_REQUEST: "GET_TRAILER_VIOLATIONS_REQUEST",
  GET_TRAILER_VIOLATIONS_SUCCESS: "GET_TRAILER_VIOLATIONS_SUCCESS",
  GET_TRAILER_VIOLATIONS_FAILURE: "GET_TRAILER_VIOLATIONS_FAILURE",
  GET_TRAILER_VIOLATIONS_CLOSE: "GET_TRAILER_VIOLATIONS_CLOSE",
  SET_TRAILER_FILTER: "SET_TRAILER_FILTER",
  CLEAN_TRAILER_FILTER: "CLEAN_TRAILER_FILTER",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  GET_ALL_DOCUMENTS_REQUEST: "GET_ALL_DOCUMENTS_REQUEST",
  GET_ALL_DOCUMENTS_SUCCESS: "GET_ALL_DOCUMENTS_SUCCESS",
  GET_ALL_DOCUMENTS_FAILURE: "GET_ALL_DOCUMENTS_FAILURE",

  GET_DOCUMENTS_REQUEST: "GET_DOCUMENTS_REQUEST",
  GET_DOCUMENTS_SUCCESS: "GET_DOCUMENTS_SUCCESS",
  GET_DOCUMENTS_FAILURE: "GET_DOCUMENTS_FAILURE",

  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAILURE: "DOWNLOAD_DOCUMENT_FAILURE",

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",

  
  POST_SAVE_TRAILER_LOGO_REQUEST: 'POST_SAVE_TRAILER_LOGO_REQUEST',
  POST_SAVE_TRAILER_LOGO_SUCCESS: 'POST_SAVE_TRAILER_LOGO_SUCCESS',
  POST_SAVE_TRAILER_LOGO_FAILURE: 'POST_SAVE_TRAILER_LOGO_FAILURE',

  RESET_MESSAGE: "RESET_MESSAGE"
};

export default TrailersConst;
