const TrucksConst = {
  GET_TRUCK_REQUEST: "GET_TRUCK_REQUEST",
  GET_TRUCK_SUCCESS: "GET_TRUCK_SUCCESS",
  GET_TRUCK_FAILURE: "GET_TRUCK_FAILURE",
  GET_TRUCK_PHOTOS_REQUEST: "GET_TRUCK_PHOTOS_REQUEST",
  GET_TRUCK_PHOTOS_SUCCESS: "GET_TRUCK_PHOTOS_SUCCESS",
  GET_TRUCK_PHOTOS_FAILURE: "GET_TRUCK_PHOTOS_FAILURE",
  GET_STATES_REQUEST: "GET_STATES_REQUEST",
  GET_STATES_SUCCESS: "GET_STATES_SUCCESS",
  GET_STATES_FAILURE: "GET_STATES_FAILURE",
  POST_SAVE_DATA_TRUCK_REQUEST: "POST_SAVE_DATA_TRUCK_REQUEST",
  POST_SAVE_DATA_TRUCK_SUCCESS: "POST_SAVE_DATA_TRUCK_SUCCESS",
  POST_SAVE_DATA_TRUCK_FAILURE: "POST_SAVE_DATA_TRUCK_FAILURE",
  POST_SAVE_DATA_TRUCK_INSURANCE_REQUEST:
    "POST_SAVE_DATA_TRUCK_INSURANCE_REQUEST",
  POST_SAVE_DATA_TRUCK_INSURANCE_SUCCESS:
    "POST_SAVE_DATA_TRUCK_INSURANCE_SUCCESS",
  POST_SAVE_DATA_TRUCK_INSURANCE_FAILURE:
    "POST_SAVE_DATA_TRUCK_INSURANCE_FAILURE",
  POST_SAVE_DATA_NOTIFICATIONS_REQUEST: "POST_SAVE_DATA_NOTIFICATIONS_REQUEST",
  POST_SAVE_DATA_NOTIFICATIONS_SUCCESS: "POST_SAVE_DATA_NOTIFICATIONS_SUCCESS",
  POST_SAVE_DATA_NOTIFICATIONS_FAILURE: "POST_SAVE_DATA_NOTIFICATIONS_FAILURE",

  NEW_DOCUMENT_TOGGLE: "NEW_DOCUMENT_TOGGLE",
  DELETE_TRUCK_DOCUMENT_TOGGLE: "DELETE_TRUCK_DOCUMENT_TOGGLE",
  POST_SAVE_TRUCK_DOCUMENT_REQUEST: "POST_SAVE_TRUCK_DOCUMENT_REQUEST",
  POST_SAVE_TRUCK_DOCUMENT_SUCCESS: "POST_SAVE_TRUCK_DOCUMENT_SUCCESS",
  POST_SAVE_TRUCK_DOCUMENT_FAILURE: "POST_SAVE_TRUCK_DOCUMENT_FAILURE",
  GET_ALL_TRUCK_DOCUMENTS_REQUEST: "GET_ALL_TRUCK_DOCUMENTS_REQUEST",
  GET_ALL_TRUCK_DOCUMENTS_SUCCESS: "GET_ALL_TRUCK_DOCUMENTS_SUCCESS",
  GET_ALL_TRUCK_DOCUMENTS_FAILURE: "GET_ALL_TRUCK_DOCUMENTS_FAILURE",
  DELETE_TRUCK_DOCUMENT_REQUEST: "DELETE_TRUCK_DOCUMENT_REQUEST",
  DELETE_TRUCK_DOCUMENT_SUCCESS: "DELETE_TRUCK_DOCUMENT_SUCCESS",
  DELETE_TRUCK_DOCUMENT_FAILURE: "DELETE_TRUCK_DOCUMENT_FAILURE",

  OPEN_ALERTS_TOGGLE: "OPEN_ALERTS_TOGGLE",
  GET_TRUCK_ALERTS_REQUEST: "GET_TRUCK_ALERTS_REQUEST",
  GET_TRUCK_ALERTS_SUCCESS: "GET_TRUCK_ALERTS_SUCCESS",
  GET_TRUCK_ALERTS_FAILURE: "GET_TRUCK_ALERTS_FAILURE",

  CLEAN: "CLEAN",
  CLEAN_MESSAGE_T: "CLEAN_MESSAGE_T",
  GET_TRUCK_INSPECTIONS_REQUEST: "GET_TRUCK_INSPECTIONS_REQUEST",
  GET_TRUCK_INSPECTIONS_SUCCESS: "GET_TRUCK_INSPECTIONS_SUCCESS",
  GET_TRUCK_INSPECTIONS_FAILURE: "GET_TRUCK_INSPECTIONS_FAILURE",
  GET_TRUCK_VIOLATIONS_REQUEST: "GET_TRUCK_VIOLATIONS_REQUEST",
  GET_TRUCK_VIOLATIONS_SUCCESS: "GET_TRUCK_VIOLATIONS_SUCCESS",
  GET_TRUCK_VIOLATIONS_FAILURE: "GET_TRUCK_VIOLATIONS_FAILURE",
  GET_TRUCK_VIOLATIONS_CLOSE: "GET_TRUCK_VIOLATIONS_CLOSE",
  SET_FILTER: "SET_FILTER",
  CLEAN_FILTER: "CLEAN_FILTER",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT",
  GET_ALL_DOCUMENTS_REQUEST: "GET_ALL_DOCUMENTS_REQUEST",
  GET_ALL_DOCUMENTS_SUCCESS: "GET_ALL_DOCUMENTS_SUCCESS",
  GET_ALL_DOCUMENTS_FAILURE: "GET_ALL_DOCUMENTS_FAILURE",

  GET_DOCUMENTS_REQUEST: "GET_DOCUMENTS_REQUEST",
  GET_DOCUMENTS_SUCCESS: "GET_DOCUMENTS_SUCCESS",
  GET_DOCUMENTS_FAILURE: "GET_DOCUMENTS_FAILURE",

  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAILURE: "DOWNLOAD_DOCUMENT_FAILURE",

  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",
  
    GET_MAINTENANCE_INSPECTIONS_TRUCK_REQUEST: "GET_MAINTENANCE_INSPECTIONS_TRUCK_REQUEST",
    GET_MAINTENANCE_INSPECTIONS_TRUCK_SUCCESS: "GET_MAINTENANCE_INSPECTIONS_TRUCK_SUCCESS",
    GET_MAINTENANCE_INSPECTIONS_TRUCK_FAILURE: "GET_MAINTENANCE_INSPECTIONS_TRUCK_FAILURE",

  RESET_MESSAGE: "RESET_MESSAGE",

  DELETE_INSPECTION_TOGGLE: 'DELETE_INSPECTION_TOGGLE',
  DELETE_INSPECTION_REQUEST: 'DELETE_INSPECTION_REQUEST',
  DELETE_INSPECTION_SUCCESS: 'DELETE_INSPECTION_SUCCESS',
  DELETE_INSPECTION_FAILURE: 'DELETE_INSPECTION_FAILURE',

  POST_SAVE_TRUCK_LOGO_REQUEST: 'POST_SAVE_TRUCK_LOGO_REQUEST',
  POST_SAVE_TRUCK_LOGO_SUCCESS: 'POST_SAVE_TRUCK_LOGO_SUCCESS',
  POST_SAVE_TRUCK_LOGO_FAILURE: 'POST_SAVE_TRUCK_LOGO_FAILURE',
};

export default TrucksConst;
