const StatsConst = {

    TOGGLE_TOAST_ALERT: 'TOGGLE_TOAST_ALERT',

    RANDOM_STATS_REQUEST: 'RANDOM_STATS_REQUEST',
    RANDOM_STATS_SUCCESS: 'RANDOM_STATS_SUCCESS',
    RANDOM_STATS_FAILURE: 'RANDOM_STATS_FAILURE',

    RANDOM_STATS_BY_YEAR_REQUEST: 'RANDOM_STATS_BY_YEAR_REQUEST',
    RANDOM_STATS_BY_YEAR_SUCCESS: 'RANDOM_STATS_BY_YEAR_SUCCESS',
    RANDOM_STATS_BY_YEAR_FAILURE: 'RANDOM_STATS_BY_YEAR_FAILURE',

    RANDOM_ALCOHOL_STATS_REQUEST: 'RANDOM_ALCOHOL_STATS_REQUEST',
    RANDOM_ALCOHOL_STATS_SUCCESS: 'RANDOM_ALCOHOL_STATS_SUCCESS',
    RANDOM_ALCOHOL_STATS_FAILURE: 'RANDOM_ALCOHOL_STATS_FAILURE',

    RANDOM_ALCOHOL_STATS_BY_YEAR_REQUEST: 'RANDOM_ALCOHOL_STATS_BY_YEAR_REQUEST',
    RANDOM_ALCOHOL_STATS_BY_YEAR_SUCCESS: 'RANDOM_ALCOHOL_STATS_BY_YEAR_SUCCESS',
    RANDOM_ALCOHOL_STATS_BY_YEAR_FAILURE: 'RANDOM_ALCOHOL_STATS_BY_YEAR_FAILURE',

    RANDOM_LIST_PDF_REQUEST: 'RANDOM_LIST_PDF_REQUEST',
    RANDOM_LIST_PDF_SUCCESS: 'RANDOM_LIST_PDF_SUCCESS',
    RANDOM_LIST_PDF_FAILURE: 'RANDOM_LIST_PDF_FAILURE',

    RANDOM_LIST_PDF_REQUEST: 'RANDOM_LIST_PDF_REQUEST',
    RANDOM_LIST_PDF_SUCCESS: 'RANDOM_LIST_PDF_SUCCESS',
    RANDOM_LIST_PDF_FAILURE: 'RANDOM_LIST_PDF_FAILURE',

    NEW_COMPANY_REQUEST: 'NEW_COMPANY_REQUEST',
    NEW_COMPANY_SUCCESS: 'NEW_COMPANY_SUCCESS',
    NEW_COMPANY_FAILURE: 'NEW_COMPANY_FAILURE',   
    
    SET_PREVIOUS_RANDOMS_REQUEST: 'SET_PREVIOUS_RANDOMS_REQUEST',
    SET_PREVIOUS_RANDOMS_SUCCESS: 'SET_PREVIOUS_RANDOMS_SUCCESS',
    SET_PREVIOUS_RANDOMS_FAILURE: 'SET_PREVIOUS_RANDOMS_FAILURE', 
  };
  
  export default StatsConst;
  