const StatsAlcoholConst = {
    RANDOM_STATS_ALCOHOL_REQUEST: 'RANDOM_STATS_ALCOHOL_REQUEST',
    RANDOM_STATS_ALCOHOL_SUCCESS: 'RANDOM_STATS_ALCOHOL_SUCCESS',
    RANDOM_STATS_ALCOHOL_FAILURE: 'RANDOM_STATS_ALCOHOL_FAILURE',

    RANDOM_LIST_PDF_ALCOHOL_REQUEST: 'RANDOM_LIST_PDF_ALCOHOL_REQUEST',
    RANDOM_LIST_PDF_ALCOHOL_SUCCESS: 'RANDOM_LIST_PDF_ALCOHOL_SUCCESS',
    RANDOM_LIST_PDF_ALCOHOL_FAILURE: 'RANDOM_LIST_PDF_ALCOHOL_FAILURE',
  };
  
  export default StatsAlcoholConst;
  