const WOConst = {
  GET_WORKORDER_REQUEST: "GET_WORKORDER_REQUEST",
  GET_WORKORDER_SUCCESS: "GET_WORKORDER_SUCCESS",
  GET_WORKORDER_FAILURE: "GET_WORKORDER_FAILURE",
  POST_SAVE_DATA_WORKORDER_REQUEST: "POST_SAVE_DATA_WORKORDER_REQUEST",
  POST_SAVE_DATA_WORKORDER_SUCCESS: "POST_SAVE_DATA_WORKORDER_SUCCESS",
  POST_SAVE_DATA_WORKORDER_FAILURE: "POST_SAVE_DATA_WORKORDER_FAILURE",
  POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_REQUEST: "POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_REQUEST",
  POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_SUCCESS: "POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_SUCCESS",
  POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_FAILURE: "POST_SAVE_DATA_WORKORDER_NEXT_INSPECTION_FAILURE",
  CLEAN: "CLEAN",
  POST_ADD_SERVICE_REQUEST: "POST_ADD_SERVICE_REQUEST",
  POST_ADD_SERVICE_SUCCESS: "POST_ADD_SERVICE_SUCCESS",
  POST_ADD_SERVICE_FAILURE: "POST_ADD_SERVICE_FAILURE",
  GET_SERVICES_REQUEST: "GET_SERVICES_REQUEST",
  GET_SERVICES_SUCCESS: "GET_SERVICES_SUCCESS",
  GET_SERVICES_FAILURE: "GET_SERVICES_FAILURE",
  DELETE_SERVICE_TOGGLE: "DELETE_SERVICE_TOGGLE",
  DELETE_SERVICE_REQUEST: "DELETE_SERVICE_REQUEST",
  DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_FAILURE: "DELETE_SERVICE_FAILURE",

  POST_ADD_MATERIAL_REQUEST: "POST_ADD_MATERIAL_REQUEST",
  POST_ADD_MATERIAL_SUCCESS: "POST_ADD_MATERIAL_SUCCESS",
  POST_ADD_MATERIAL_FAILURE: "POST_ADD_MATERIAL_FAILURE",
  GET_MATERIALES_REQUEST: "GET_MATERIALES_REQUEST",
  GET_MATERIALES_SUCCESS: "GET_MATERIALES_SUCCESS",
  GET_MATERIALES_FAILURE: "GET_MATERIALES_FAILURE",
  DELETE_MATERIAL_TOGGLE: "DELETE_MATERIAL_TOGGLE",
  DELETE_MATERIAL_REQUEST: "DELETE_MATERIAL_REQUEST",
  DELETE_MATERIAL_SUCCESS: "DELETE_MATERIAL_SUCCESS",
  DELETE_MATERIAL_FAILURE: "DELETE_MATERIAL_FAILURE",

  DOWNLOAD_DOCUMENT_REQUEST: "DOWNLOAD_DOCUMENT_REQUEST",
  DOWNLOAD_DOCUMENT_SUCCESS: "DOWNLOAD_DOCUMENT_SUCCESS",
  DOWNLOAD_DOCUMENT_FAILURE: "DOWNLOAD_DOCUMENT_FAILURE",

  GET_WORKORDER_IMAGES_REQUEST: "GET_WORKORDER_IMAGES_REQUEST",
  GET_WORKORDER_IMAGES_SUCCESS: "GET_WORKORDER_IMAGES_SUCCESS",
  GET_WORKORDER_IMAGES_FAILURE: "GET_WORKORDER_IMAGES_FAILURE",

  TOGGLE_TOAST_ALERT: "TOGGLE_TOAST_ALERT"
};

export default WOConst;
