export const GET_PROFILE_COMPANY = "GET_PROFILE_COMPANY"
export const GET_PROFILE_COMPANY_SUCCESS = "GET_PROFILE_COMPANY_SUCCESS"
export const GET_PROFILE_COMPANY_FAIL = "GET_PROFILE_COMPANY_FAIL"

  
export const ADD_PROFILE = "ADD_PROFILE";
export const ADD_PROFILE_SUCCESS = "ADD_PROFILE_SUCCESS";
export const ADD_PROFILE_FAILURE = "ADD_PROFILE_FAILURE";

export const DELETE_PROFILE = "DELETE_PROFILE";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAILURE = "DELETE_PROFILE_FAILURE";

export const EDIT_PROFILE = "EDIT_PROFILE";
export const START_PROFILE_EDITION = "START_PROFILE_EDITION";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
