export const GET_DATA_DRIVER2_REQUEST = "GET_DATA_DRIVER2_REQUEST";
export const GET_DATA_DRIVER2_SUCCESS = "GET_DATA_DRIVER2_SUCCESS";
export const GET_DATA_DRIVER2_FAILURE = "GET_DATA_DRIVER2_FAILURE";